### ISSUE TITLE
Multiple incudePath paths?

### ISSUE THREAD

**Issue by IainAndrew** [vanetix/grunt-includes#32]
Loving this plugin, thanks for making it. Is there a way to have multiple includePath paths? I'd like to have template files in a 'components' directory as well as a 'partials' directory, for example.

**Comment by vanetix** [comment]
Not currently, but I have done a similar thing with separate grunt configs or nested folders (makes it more verbose, but helps me organize). For example, I will just create two directories under that path so it looks like:
```
includes/
   components/
   partials/
```
I understand this might not be the wanted functionality, since you would rather just have `a.html` as opposed to `components/a.html`. 

Although we could make `includePath` either a string, like it is currently or an array `['includes/components', 'includes/partials']` so that `includes/components` will be searched first, if the file doesn't exist, use the next path... etc. Does that make sense?

**Comment by IainAndrew** [comment]
I should have thought to just nest the folders like that. It's not a bad solution, I think it actually makes more sense to have the folder name as well as file name, if the partials are separated out like that.
Your latter suggestion would probably be ideal though, as it would allow you to use both solutions.

**Comment by vanetix** [comment]
Thanks for the suggestion, support for an array value was added in d16df8b62b30808c1b6f4f91afdb817d1f294b0d

**Comment by IainAndrew** [comment]
Excellent, thank you!
